apiVersion: v1
kind: Service
metadata:
  name: flyte-binary-grpc-nodeport
  namespace: flyte
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 8089
      nodePort: 31081
  selector:
    app.kubernetes.io/name: flyte-binary
---
apiVersion: v1
kind: Service
metadata:
  name: flyte-binary-http-nodeport
  namespace: flyte
spec:
  type: NodePort
  ports:
    - name: http
      port: 8088
      nodePort: 31082
  selector:
    app.kubernetes.io/name: flyte-binary
---
apiVersion: v1
kind: Service
metadata:
  name: flyte-binary-webhook-nodeport
  namespace: flyte
spec:
  type: NodePort
  ports:
    - name: webhook
      port: 443
      nodePort: 31083
  selector:
    app.kubernetes.io/name: flyte-binary